### PR TITLE
Fixes remount /tmp typo

### PR DESCRIPTION
**Pull request by dderemiah**
**Overall Review of Changes:**
Fixes capitalization for handler notify
**Issue Fixes:**
Fixes capitalization for handler notify

**Enhancements:**

**How has this been tested?:**
tested on my servers

### CODE REVIEW

**Comment by uk-bolly** [comment]
hi @dderemiah 

Thank you for highlighting this issue and raising the subsequent PR. i have however noticed that the commit is not signed-off by for gpg signed which are requirements as per the contributing guidelines.
If you could fix this i am happy to accept the PR.

Many thanks

uk-bolly

**Comment by dderemiah** [comment]
I followed the directions I could find on signing PR's.  Hopefully it worked.

**Comment by uk-bolly** [comment]
hi @dderemiah 

Thank you for following up on this its almost there, this can be a little confusing. The commit is now signed-off-by but it would still need to be signed.
The following article may help. It also shows how it appears in the PR with the verified logo next to it once it is gpg signed.

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

many thanks

uk-bolly

**Comment by dderemiah** [comment]
It says the commit is signed.  I think I got it done.  Thanks

**Review by uk-bolly — APPROVED** [review]
good catch

**Pull request merged**
